### ISSUE TITLE
Style of editor content needs update

### ISSUE THREAD

**Issue by judyshyu** [purple1007/jnews-child#4]
**文章編輯器區塊樣式待更新：**

1. li 文字顏色應與全站文字顏色統一
2. Enlighter 區塊，第一行文字前方有多餘的空隙
3. code 目前只有包在 p 內時有正確顯示樣式；code 字體大小應些微縮減、左右padding縮減、左右margin增加
4. pre 字體須將中文字體排在 Courier 之前，避免部分文字吃到 serif 字體

**Comment by purple1007** [comment]
追加需求：
- 桌機版的文章預覽 block ， 圖片與右邊文章資訊間距調小，調整至 `20px`。

<img width="767" alt="截圖 2020-11-10 下午3 03 23" src="https://user-images.githubusercontent.com/40792376/98640932-e2e10980-2365-11eb-84c7-0e8c17f07d82.png">

**Comment by purple1007** [comment]
另外，可以在完成的 commit 裡寫上這個 issue 的編號 (#4)，這樣在推上來時，這個 issue 就會顯示是哪一條分支正在解決這一個 issue 。
合併時選擇 `squash and merge` 如下圖：
<img width="209" alt="截圖 2020-11-10 下午3 10 02" src="https://user-images.githubusercontent.com/40792376/98641492-d14c3180-2366-11eb-8ea9-2325a5400248.png">
 這樣在合併時就不會多產生一個合併的 commit 而是將分支的 commit 變成一個 commit 然後合併到 master ，這在 master 的 commit 會看起來比較簡潔。

**Comment by purple1007** [comment]
Finished on PR: #5
